CREATE TABLE USER(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NAME TEXT UNIQUE,
	PASSWORD TEXT,
	IS_ADMIN INTEGER
);

CREATE TABLE ACTION(
	ID INTEGER PRIMARY KEY NOT NULL,
	EXEC_DATE DATE,
	EXEC_USER INTEGER,
	EXEC_CMD TEXT,
	FOREIGN KEY(EXEC_USER) REFERENCES USER(ID) ON DELETE CASCADE,
	FOREIGN KEY(EXEC_CMD) REFERENCES CMD(NAME) ON DELETE CASCADE
);

CREATE TABLE CMD(
	NAME TEXT PRIMARY KEY NOT NULL,
	SUMMARY TEXT,
	SYNOPSIS TEXT,
	DESC TEXT
);

CREATE TABLE OPTION (
    KEY CHAR(1) NOT NULL,
    DESC TEXT,
    CMD_NAME TEXT NOT NULL,
    PRIMARY KEY (KEY, CMD_NAME),
    FOREIGN KEY (CMD_NAME) REFERENCES CMD(NAME) ON DELETE CASCADE
);
