CREATE TABLE USER(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NAME TEXT UNIQUE,
	PASSWORD TEXT,
	IS_ADMIN INTEGER
);

CREATE TABLE CMD(
	NAME TEXT PRIMARY KEY NOT NULL,
	SUMMARY TEXT,
	SYNOPSIS TEXT,
	DESC TEXT
);

CREATE TABLE OPTION (
    KEY CHAR(1) NOT NULL,
    DESC TEXT,
    CMD_NAME TEXT NOT NULL,
    PRIMARY KEY (KEY, CMD_NAME),
    FOREIGN KEY (CMD_NAME) REFERENCES CMD(NAME) ON DELETE CASCADE
);
